### ISSUE TITLE
umount error running example.yaml: target is busy

### ISSUE THREAD

**Issue by is-jburkhardt** [mwhudson/livefs-editor#16]
I'm trying to get this up and running - looks very promising for my use case.
(needed to install python-apt-dev, initramfs-tools and python3-debian)

I hopefully have an environment setup correctly. I cloned this repo today (561e3d), built the wheel and installed into a venv (as root)

I am working with the 18.04.6 server live image on a 22.04.1 host.

Running the example.yaml actions.

The add-packages-to-pool action runs and then I this this error:

```
    running resign-pool with arguments {}                                                                                                                              
gpg: WARNING: unsafe permissions on homedir '/tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp'                                                                                        gpg: keybox '/tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp/pubring.kbx' created
gpg: /tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp/trustdb.gpg: trustdb created                                                                                                    gpg: key 1D9479026C00BBA2 marked as ultimately trusted                                                                                                                
gpg: directory '/tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp/openpgp-revocs.d' created                                                                                            gpg: revocation certificate stored as '/tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp/openpgp-revocs.d/BACF010B2B102F162E3C14D01D9479026C00BBA2.rev'                                
gpg: WARNING: unsafe permissions on homedir '/tmp/tmpxcdchbi0/.tmp/tmp94dn9ngp'                                                                                             
 squashfs 'filesystem' now mounted at '/tmp/tmpxcdchbi0/new/filesystem'                                                                                          
umount: /tmp/tmpxcdchbi0/.tmp/tmpr327mgwo: target is busy.                                                                                                             
Traceback (most recent call last):                                                                                                                                       
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/__main__.py", line 65, in main                                                                  func(ctxt, **kw)                                                                                                                                                    
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 41, in impl                                                                   return func(ctxt, **kw)                                                                                                                                             
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 450, in add_packages_to_pool                                                  add_debs_to_pool(ctxt, debs=debs)                                                                                                                                   
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 41, in impl                                                                   return func(ctxt, **kw)
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 404, in add_debs_to_pool
    resign_pool(ctxt)
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 41, in impl
    return func(ctxt, **kw)
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/actions.py", line 359, in resign_pool
    new_fs = ctxt.edit_squashfs(get_squash_names(ctxt)[0])
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/context.py", line 201, in edit_squashfs
    self.add_sys_mounts(target)
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/context.py", line 121, in add_sys_mounts
    mnts.append(self.add_mount(typ, typ, f'{mountpoint}/{relpath}'))
File "/home/x/xx/venv/lib/python3.10/site-packages/livefs_edit/context.py", line 103, in add_mount
    os.makedirs(mountpoint)
File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmpxcdchbi0/new/filesystem/sys/kernel/security'
```

**Comment by is-jburkhardt** [comment]
> File "/usr/lib/python3.10/os.py", line 225, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 1] Operation not permitted: '/tmp/tmpxcdchbi0/new/filesystem/sys/kernel/security'
> ```

Digging around a bit and added a call to `cache.close()` in `action.py:451`

That made the umount error go away (no idea if this is the right thing to do here but that was the overly dir involved). That seems to be a red herring because I'm still getting a crash with the same callstack.

**Comment by is-jburkhardt** [comment]
I had tried this originally under WSL2 and I think that kernel is locked down - tried adjusting security settings but that didn't help. Set up a new VM with fresh Ubuntu 22.04 and created an iso with no errors.

**Comment by mwhudson** [comment]
Ah I should probably only try to bind mount these sysfs dirs into the chroot if they exist on the host. Does `/sys/kernel/security` exist when running the WSL2 kernel?

**Comment by mwhudson** [comment]
Could you try https://github.com/mwhudson/livefs-editor/pull/17 and see if that helps?

**Comment by is-jburkhardt** [comment]
> Could you try #17 and see if that helps?

yes! can build from example.yaml successfully now. Thank you.

**Comment by mwhudson** [comment]
Thanks for testing!
