### ISSUE TITLE
Specifying package versions does not work

### ISSUE THREAD

**Issue by oregonpillow** [mwhudson/livefs-editor#21]
When i specify a specific package version i get the error: `raise KeyError('The cache has no package named %r' % key)`

```
Traceback (most recent call last):
  File "<redacted>/__main__.py", line 65, in main
    func(ctxt, **kw)
  File "/usr/local/lib/python3.10/dist-packages/livefs_edit/actions.py", line 41, in impl
    return func(ctxt, **kw)
  File "/usr/local/lib/python3.10/dist-packages/livefs_edit/actions.py", line 443, in add_packages_to_pool
    cache[p].mark_install()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 283, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'tpm2-tools=5.2-1build1'"
```

any suggestions?

**Comment by mwhudson** [comment]
I know you closed this as you found another way to do things but it would be nice if this worked.
