### ISSUE TITLE
Is it possible to add package for other architecture?

### ISSUE THREAD

**Issue by crusaderflex** [mwhudson/livefs-editor#33]
I would add i386 packages in a amd64 env

 marking gcc-12-base:amd64 for installation
  marking gcc-12-base:i386 for installation
umount: /tmp/tmp6jxb37wm/.tmp/tmpq3fmbvnn: target is busy.
umount: /tmp/tmp6jxb37wm/old/iso: target is busy.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 281, in __getitem__
    rawpkg = self._cache[key]
KeyError: 'gcc-12-base:i386'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/arloba/livefs-editor/livefs_edit/__main__.py", line 100, in <module>
    main(sys.argv[1:])
  File "/home/arloba/livefs-editor/livefs_edit/__main__.py", line 82, in main
    func(ctxt, **kw)
  File "/home/arloba/livefs-editor/livefs_edit/actions.py", line 58, in impl
    return func(ctxt, **kw)
  File "/home/arloba/livefs-editor/livefs_edit/actions.py", line 484, in add_packages_to_pool
    cache[p].mark_install()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 283, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'gcc-12-base:i386'"

Ubuntu could download the file:

#~/livefs-editor$ apt download gcc-12-base:i386
Holen:1 http://archive.ubuntu.com/ubuntu jammy-updates/main i386 gcc-12-base i386 12.1.0-2ubuntu1~22.04 [19,0 kB]
Es wurden 19,0 kB in 1 s geholt (23,8 kB/s).

Could livefs-editor configured to use "foreign-architectures"

I would be great if you can look at it.

Greets Michael

**Comment by mwhudson** [comment]
Ah yes, I think the issue here is that I just interpret the argument to --add-packages-to-pool as a package name, I should be smarter about that. If you download the packages by hand and pass them to --add-debs-to-pool does that work? I think it probably will.

**Comment by mwhudson** [comment]
Ah i think i was a bit wrong there, need a bit more of a look...
