### ISSUE TITLE
Cross-arch iso modification

### ISSUE THREAD

**Issue by ThibF** [mwhudson/livefs-editor#52]
Currently, livefs-editor is directly chroot-ing into the given livefs which isn't working in the case of cross platform modification (of a raspberry pi image would be a good example).

Here is the log:
```
➜ livefs_edit ubuntu-23.10.1-desktop-arm64+x13s.iso modified.iso --install-debs /tmp/e394e7c3b27d.efdj/*.deb
set up loop device /dev/loop26 backing ubuntu-23.10.1-desktop-arm64+x13s.iso
found live iso9660 filesystem on /dev/loop26p1
running install-debs with arguments {'debs': ['/tmp/e394e7c3b27d.efdj/1.deb', '/tmp/e394e7c3b27d.efdj/2.deb', '/tmp/e394e7c3b27d.efdj/3.deb', '/tmp/e394e7c3b27d.efdj/4.deb']}
  running setup-rootfs with arguments {}
chroot: failed to run command ‘dpkg’: Exec format error
Traceback (most recent call last):
  File "/home/thibf/canonical/livefs-editor/livefs_edit/__main__.py", line 87, in main
    func(ctxt, **kw)
  File "/home/thibf/canonical/livefs-editor/livefs_edit/actions.py", line 57, in impl
    return func(ctxt, **kw)
           ^^^^^^^^^^^^^^^^
  File "/home/thibf/canonical/livefs-editor/livefs_edit/actions.py", line 189, in install_debs
    ctxt.run(['chroot', rootfs, 'dpkg', '-i', deb_name])
  File "/home/thibf/canonical/livefs-editor/livefs_edit/context.py", line 81, in run
    cp = subprocess.run(cmd, check=check, **kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['chroot', '/tmp/tmplhyge94k/rootfs', 'dpkg', '-i', 'foo.deb']' returned non-zero exit status 126.
umount: /tmp/tmplhyge94k/old/iso: target is busy.
```

Maybe a first step toward this problem would be to fail gracefully by detecting the host arch and the image type, then rely on qemu to execute embedded binaries.

**Comment by mwhudson** [comment]
I don't know what the best answer to this is. You could install qemu-user-static and then it will probably work ok?

**Comment by ThibF** [comment]
It doesn't work because when we chroot into the iso, these hosts binary aren't available anymore. We could install in the target, but that would either require cleanup or increase the size of the image.
I propose an cmdline argument to support this use case.

**Comment by ThibF** [comment]
Indeed my binfmt wasn't correctly configured, it works well in that case.
