### ISSUE TITLE
Kernel change not working with Ubuntu 24 Desktop Image

### ISSUE THREAD

**Issue by b1saul** [mwhudson/livefs-editor#60]
Hi,

I'm want to do.
`
- name: replace-kernel
  flavor: lowlatency
`
but i get
`
Creating config file /etc/default/grub with new version
Processing triggers for dbus (1.14.10-4ubuntu4) ...
Processing triggers for install-info (7.1-3build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for initramfs-tools (0.142ubuntu25) ...
Processing triggers for linux-image-6.8.0-36-lowlatency (6.8.0-36.36.1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.8.0-36-lowlatency
Clearing symlinks in /var/tmp/mkinitramfs_buu2Rv/etc/ssl/certs...
done.
Updating certificates in /var/tmp/mkinitramfs_buu2Rv/etc/ssl/certs...
146 added, 0 removed; done.
mv: cannot stat '/tmp/tmp9gapavyz/.tmp/tmplggwatc7/main/conf/uuid.conf': No such file or directory
Traceback (most recent call last):
  File "/home/saul/test/livefs-editor/livefs_edit/__main__.py", line 87, in main
    func(ctxt, **kw)
  File "/home/saul/test/livefs-editor/livefs_edit/actions.py", line 57, in impl
    return func(ctxt, **kw)
           ^^^^^^^^^^^^^^^^
  File "/home/saul/test/livefs-editor/livefs_edit/actions.py", line 726, in replace_kernel
    ctxt.run([
  File "/home/saul/test/livefs-editor/livefs_edit/context.py", line 82, in run
    cp = subprocess.run(cmd, check=check, **kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mv', '/tmp/tmp9gapavyz/.tmp/tmplggwatc7/main/conf/uuid.conf', '/tmp/tmp9gapavyz/new/iso/.disk/casper-uuid-custom']' returned non-zero exit status 1.
umount: /tmp/tmp9gapavyz/.tmp/tmpkjafttkd: target is busy.
umount: /tmp/tmp9gapavyz/old/iso: target is busy.
`

Build system is a freshly installed Ubuntu 24.

**Comment by mwhudson** [comment]
Yeah, I don't think replace-kernel has ever worked on desktop ISOs unfortunately.

**Comment by b1saul** [comment]
Do you see any chance to make it work or is there a hard block which would render it impossible?

If it is possible me or a co-worker could have a look into it, if you like.

**Comment by mwhudson** [comment]
No blocker I'm aware of, it'll just be fiddly and annoying I expect.
