### ISSUE TITLE
 --add-packages-to-pool linux-generic-hwe-24.04 errors out

### ISSUE THREAD

**Issue by jw-rav** [mwhudson/livefs-editor#64]
```
sudo PYTHONPATH=~/livefs-editor python3 -m livefs_edit --debug /var/tmp/images/ubuntu-24.04.1-live-server-amd64.iso /var/tmp/builds/ubuntu-remaster/ubuntu-24.04.1-live-server-amd64.iso --add-packages-to-pool linux-generic-hwe-24.04
```
gives:
```
/usr/lib/python3/dist-packages/apt/cache.py:562: Warning: W:Download is performed unsandboxed as root as file '/tmp/tmpmotkdsmc/.tmp/tmpkw3fe67s/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_noble_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
  res = self._cache.update(fetch_progress, slist, pulse_interval)
  ** updating apt lists done **
  marking linux-generic-hwe-24.04 for installation
```
and later:
```
Original exception was:                                                                                                                   
Traceback (most recent call last):                                                                                                        
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                 
  File "<frozen runpy>", line 88, in _run_code                                                                                            
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/__main__.py", line 105, in <module>                    
    main(sys.argv[1:])                                                                                                                    
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/__main__.py", line 87, in main                         
    func(ctxt, **kw)                                                                                                                      
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/actions.py", line 57, in impl                          
    return func(ctxt, **kw)                                                                                                               
           ^^^^^^^^^^^^^^^^
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/actions.py", line 526, in add_packages_to_pool
    add_debs_to_pool(ctxt, debs=debs)
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/actions.py", line 57, in impl
    return func(ctxt, **kw)
           ^^^^^^^^^^^^^^^^
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/actions.py", line 443, in add_debs_to_pool
    cp = ctxt.run(
         ^^^^^^^^^
  File "/m/s/rep/git-svn/gemedis-dev/remaster1/subiquity/livefs-editor/livefs_edit/context.py", line 86, in run
    msg += f" {len(cp.stderr)} bytes of output"
               ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

AFAICS, second (fatal) error happens only with --debug option

**Comment by mwhudson** [comment]
I fixed the logging thing. I think the command would have succeeded without --debug though? It works for me.

**Comment by jw-rav** [comment]
Yes, command works without the --debug flag.

Thanks!

**Comment by jw-rav** [comment]
Sorry, forgot to mention that if the first error (the permission denied thing) is something to be expected, then this issue can probably be closed.

**Comment by mwhudson** [comment]
Thanks for getting back to me on that
